### PR TITLE
Add perl REPL support

### PR DESCRIPTION
**Pull request by amacleay**
This works as long as the client has "re.pl" installed (which is the default for me in Linux; I'm not entirely sure whether this works the same for Macs).

I'm not certain that the use of the "magic word" package_base is entirely appropriate; I'm far from a python ninja.  Feedback welcome!

### CODE REVIEW

**Comment by jcartledge** [comment]
Thanks! I'll take a look at this. I can see as we add REPLs we're going to need documentation for the idiosyncrasies of each - what you need to install etc.

**Comment by amacleay** [comment]
To wit:
<code>cpan -i Devel::REPL</code>
or
<code>apt-get install libdevel-repl-perl</code>

**Comment by jcartledge** [comment]
OK - I have a way to avoid overriding `cwd` with `package_base`: basically define a template var we can use in the config. See https://gist.github.com/jcartledge/5930995

The problem I'm having now is it's not easy to get re.pl working nicely on Mac.

**Comment by jcartledge** [comment]
I've just pushed 0.8.0 with this in it - should be in Package Control soon. Thanks :)

**Comment by amacleay** [comment]
Aah much better.

Having any specific trouble with the mac? Anything I might be able to check
into?

**Comment by jcartledge** [comment]
I worked it out eventually thanks :) Just fighting with CPAN, then I was running into trouble with plugins because I didn't have a Term::ReadLine implementation installed.

**Pull request merged**
