### PR TITLE
Windows support (highly experimental)

### PR DESCRIPTION
**Pull request by timonwong**
Here's an highly experimental branch, I have only tested some simple javascript/python scripts, it should work, but may have tons of bugs in.
Feel free to close it if it crash too much.

### CODE REVIEW

**Comment by jcartledge** [comment]
!!!

**Comment by jcartledge** [comment]
Reloading plugin C:\Users\Admin\AppData\Roaming\Sublime Text 2\Packages\sublime-worksheet\worksheet.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\worksheet.py", line 11, in <module>
    import repl
  File ".\repl__init__.py", line 5, in <module>
    from .repl import get_repl
  File ".\repl\repl.py", line 7, in <module>
    from .ftfy import fix_text
  File ".\repl\ftfy__init__.py", line 11, in <module>
    import unicodedata
ImportError: No module named unicodedata

**Comment by timonwong** [comment]
@jcartledge 
I forgot to add search path to where sublime_text.exe locates, it will be addressed soon.

**Comment by jcartledge** [comment]
Haha I just found the answer on your blog http://theo.im/blog/2012/10/25/workaround-failed-to-import-unicodedata-in-sublime-text-2-under-windows/

**Comment by jcartledge** [comment]
Thanks Timon, this is so cool.

**Comment by timonwong** [comment]
@jcartledge 
Still tons of bugs..., Non-executables don't work at all at the moment, this is done and I'll fire a new pull request later. What really annoying is, some repls, require additional  environment variable set, for example, `scala.bat` requires `EMACS=1` in the env, or it will detach after printing welcome message.

**Comment by jcartledge** [comment]
We can add an env section to the config and pass it through to pexpect - this should be straightforward as long as it doesn't adversely affect other platforms, so e.g.:

``` json
        "Scala": {
            "cmd": "scala",
            "env": {"EMACS": "1"},
            "prompt": ["scala> ", "     \\| "],
            "error": ["<console>:[0-9]+: error:"]
        }
```

Is that what you were thinking? I guess if we need platform-specific ones we could do that too - `win32_env`, `darwin_env` etc and mix as required in repl.py before spawning.

**Pull request merged**
