### PR TITLE
Add scheme racket

### PR DESCRIPTION
**Pull request by tlehman**
Add Scheme (Racket) support

Note: Still need to handle empty lines, Scheme interpreters pause on empty lines.

### CODE REVIEW

**Comment by jcartledge** [comment]
This is cool - thanks! Not sure how to handle the empty lines - do you have any ideas?

**Comment by tlehman** [comment]
We could intercept the empty lines before they get passed to the interpreter, letting it be a no-op. I haven't delved into the python code very deeply, I will implement this and push it up.

**Comment by jcartledge** [comment]
Check how PHP is configured - it ignores lines with '<?php' or '?>' (i.e. doesn't send them to the interpreter) because the interpreter chokes on them, but we need them in the editor for syntax to work.

I haven't tried it, but it might be as simple as adding:

```
"ignore": ["^$"]
```

to the racket config.

**Comment by tlehman** [comment]
@jcartledge That worked! I noticed that it doesn't insert the results as comments, I assume that is what the prefix key is right?

**Comment by jcartledge** [comment]
OK, I finally got a bit of time to look at this.
Here's what works for me:

```
    "Racket": {
        "cmd": "guile",
        "prompt": ["guile>"],
        "prefix": ";; > ",
        "error": ["ERROR:"],
        "ignore": ["^[\\s]*\n", "^[\\s]*;;"]
    }
```
- `prompt`, `error` and `ignore` need to be arrays of strings, even if there is only one value.
- I've added an angle bracket to `prefix`. It needs something to distinguish it from a regular comment because it's used in the `Clear previous results` command to match lines. If it's not distinguished all comments will get deleted.
- The interpreter hangs on lines beginning with a comment as well as empty lines. I guess it throws the comment away and then the line is empty? Lines which only contain whitespace are a problem as well, so I updated the regex to catch them.

Can you please:
- Check that works at your end, and update your branch to the working version,
- Ensure the languages under "worksheet_languages" are sorted alphabetically (so Racket comes before Ruby - it's anal, I know,) and
- Rebase against master - it's changed slightly since the original pull request.

Then we should be good to go! Thanks for making the effort - I really appreciate it.

**Comment by tlehman** [comment]
I verified that it works on my end, sorted the list of languages and then rebased off your new master branch, we should be good to merge. 

Working on this is my pleasure, this is just the kind of functionality I've been missing in ST2 that Emacs had going for it. I like the sublime-worksheet approach more though, since it is much easier to work with than Lisp.

**Comment by jcartledge** [comment]
This is in master and will be in the next release going out in a day or so.

**Comment by tlehman** [comment]
@jcartledge Will that release be available to the ST2 package manager?

**Comment by jcartledge** [comment]
Yes it will.

**Comment by tlehman** [comment]
Awesome

**Pull request merged**
