### PR TITLE
Attempt to make plugin compatible with both ST2 and ST3

### PR DESCRIPTION
**Pull request by timonwong**

### CODE REVIEW

**Comment by jcartledge** [comment]
Awesome :smile: 
Looks good to me, but let's make sure it works for everyone before we merge it.
Thanks so much for your contribution, very cool.

**Comment by pahen** [comment]
Seems to work for me :) I tested it against JS code.

**Comment by leostera** [comment]
Can we have the patch applied on a separate branch?

**Comment by jcartledge** [comment]
@leostera https://github.com/jcartledge/sublime-worksheet/tree/st3
@timonwong love your work - I'm running this now, will merge and release later today if nothing breaks.

**Pull request merged**
